export const pfData6 = [
    // {
    //   type: "Cloud VPS V4",
    //   rs: "₹3500",
    //   tx: "Basic features:",
    //   ft: [
    //     "4 vCore CPU",
    //     "4 GB RAM",
    //     "4 User s Pack",
    //     "100 GB Storage",
    //     "Daily BackUp",
    //     "speed upto 100Mbps",
    //     "99.9% uptime",
    //     "24*7 Support",
    //   ],
    // },
    // {
    //   type: "Cloud VPS Premium",
    //   rs: "₹7500",
    //   tx: "Basic features:",
    //   ft: [
    //     "6 vCore CPU",
    //     "8 GB RAM",
    //     "8 User s Pack",
    //     "200 GB Storage",
    //     "Daily BackUp",
    //     "speed upto 100Mbps",
    //     "99.9% uptime",
    //     "24*7 Support",
    //   ],
    // },
  
    // {
    //   type: "Cloud VPS V8",
    //   rs: "₹15000",
    //   tx: "Basic features:",
    //   ft: [
    //     "8 vCore CPU",
    //     "16 GB RAM",
    //     "15 User s Pack",
    //     "400 GB Storage",
    //     "Daily BackUp",
    //     "speed upto 100Mbps",
    //     "99.9% uptime",
    //     "24*7 Support",
    //   ],
    // },
  
    {
      server: "GPU CLOUD SERVER",
      type: "Cloud VPS V8",
      rs: "₹7000",
      tx: "Basic features:",
      ft: [
        "8 vCore CPU",
        "4 GB RAM",
        "150 GB Storage",
        "Daily BackUp",
        "speed upto 100Mbps",
        "99.9% uptime",
        "24*7 Support",
      ],
    },
    {
      server: "GPU CLOUD SERVER",
      type: "Cloud VPS V16",
      rs: "₹14000",
      tx: "Basic features:",
      ft: [
        "16 vCore CPU",
        "32GB RAM",
        "200 GB Storage",
        "Daily BackUp",
        "speed upto 100Mbps",
        "99.9% uptime",
        "24*7 Support",
      ],
    },
    {
      server: "GPU CLOUD SERVER",
      type: "Cloud VPS V20",
      rs: "₹24000",
      tx: "Basic features:",
      ft: [
        "20 vCore CPU",
        "64 GB RAM",
        "400 GB Storage",
        "Daily BackUp",
        "speed upto 100Mbps",
        "99.9% uptime",
        "24*7 Support",
      ],
    },
  ];

  export const pfData7 = [
    // {
    //   type: "Cloud VPS V4",
    //   rs: "₹3500",
    //   tx: "Basic features:",
    //   ft: [
    //     "4 vCore CPU",
    //     "4 GB RAM",
    //     "4 User s Pack",
    //     "100 GB Storage",
    //     "Daily BackUp",
    //     "speed upto 100Mbps",
    //     "99.9% uptime",
    //     "24*7 Support",
    //   ],
    // },
    // {
    //   type: "Cloud VPS Premium",
    //   rs: "₹7500",
    //   tx: "Basic features:",
    //   ft: [
    //     "6 vCore CPU",
    //     "8 GB RAM",
    //     "8 User s Pack",
    //     "200 GB Storage",
    //     "Daily BackUp",
    //     "speed upto 100Mbps",
    //     "99.9% uptime",
    //     "24*7 Support",
    //   ],
    // },
  
    // {
    //   type: "Cloud VPS V8",
    //   rs: "₹15000",
    //   tx: "Basic features:",
    //   ft: [
    //     "8 vCore CPU",
    //     "16 GB RAM",
    //     "15 User s Pack",
    //     "400 GB Storage",
    //     "Daily BackUp",
    //     "speed upto 100Mbps",
    //     "99.9% uptime",
    //     "24*7 Support",
    //   ],
    // },
  
    {
      server: "GPU CLOUD SERVER",
      type: "Cloud VPS V8",
      rs: "₹7000",
      tx: "Basic features:",
      ft: [
        "8 vCore CPU",
        "4 GB RAM",
        "150 GB Storage",
        "Daily BackUp",
        "speed upto 100Mbps",
        "99.9% uptime",
        "24*7 Support",
      ],
    },
    {
      server: "GPU CLOUD SERVER",
      type: "Cloud VPS V16",
      rs: "₹14000",
      tx: "Basic features:",
      ft: [
        "16 vCore CPU",
        "32GB RAM",
        "200 GB Storage",
        "Daily BackUp",
        "speed upto 100Mbps",
        "99.9% uptime",
        "24*7 Support",
      ],
    },
    {
      server: "GPU CLOUD SERVER",
      type: "Cloud VPS V20",
      rs: "₹24000",
      tx: "Basic features:",
      ft: [
        "20 vCore CPU",
        "64 GB RAM",
        "400 GB Storage",
        "Daily BackUp",
        "speed upto 100Mbps",
        "99.9% uptime",
        "24*7 Support",
      ],
    },
  ];
  
  