export const pfData = [
  {
    type: "Cloud VPS V4",
    rs: "₹2950",
    tx: "Basic features:",
    xx: "User / Month",
    ft: [
      "4 vCore CPU",
      "4 GB RAM",
      "4 User s Pack",
      "100 GB Storage",
      "Daily BackUp",
      "speed upto 100Mbps",
      "99.9% uptime",
      "24*7 Support",
    ],
  },
  {
    type: "Cloud VPS Premium",
    rs: "₹6000",
    xx: "User / Month",
    tx: "Basic features:",
    ft: [
      "6 vCore CPU",
      "8 GB RAM",
      "8 User s Pack",
      "200 GB Storage",
      "Daily BackUp",
      "speed upto 100Mbps",
      "99.9% uptime",
      "24*7 Support",
    ],
  },

  {
    type: "Cloud VPS V8",
    rs: "₹11500",
    xx: "User / Month",
    tx: "Basic features:",
    ft: [
      "8 vCore CPU",
      "16 GB RAM",
      "15 User s Pack",
      "400 GB Storage",
      "Daily BackUp",
      "speed upto 100Mbps",
      "99.9% uptime",
      "24*7 Support",
    ],
  },
  // {
  //   server: "GPU CLOUD SERVER",
  //   type: "Cloud VPS V8",
  //   rs: "₹7000",
  //   tx: "Basic features:",
  //   ft: [
  //     "8 vCore CPU",
  //     "4 GB RAM",
  //     "150 GB Storage",
  //     "Daily BackUp",
  //     "speed upto 100Mbps",
  //     "99.9% uptime",
  //     "24*7 Support",
  //   ],
  // },
  // {
  //   server: "GPU CLOUD SERVER",
  //   type: "Cloud VPS V16",
  //   rs: "₹14000",
  //   tx: "Basic features:",
  //   ft: [
  //     "16 vCore CPU",
  //     "32GB RAM",
  //     "200 GB Storage",
  //     "Daily BackUp",
  //     "speed upto 100Mbps",
  //     "99.9% uptime",
  //     "24*7 Support",
  //   ],
  // },
  // {
  //   server: "GPU CLOUD SERVER",
  //   type: "Cloud VPS V20",
  //   rs: "₹24000",
  //   tx: "Basic features:",
  //   ft: [
  //     "20 vCore CPU",
  //     "64 GB RAM",
  //     "400 GB Storage",
  //     "Daily BackUp",
  //     "speed upto 100Mbps",
  //     "99.9% uptime",
  //     "24*7 Support",
  //   ],
  // },
];

export const pfData1 = [
  // {
  //   type: "Cloud VPS V4",
  //   rs: "₹3500",
  //   tx: "Basic features:",
  //   ft: [
  //     "4 vCore CPU",
  //     "4 GB RAM",
  //     "4 User s Pack",
  //     "100 GB Storage",
  //     "Daily BackUp",
  //     "speed upto 100Mbps",
  //     "99.9% uptime",
  //     "24*7 Support",
  //   ],
  // },
  // {
  //   type: "Cloud VPS Premium",
  //   rs: "₹7500",
  //   tx: "Basic features:",
  //   ft: [
  //     "6 vCore CPU",
  //     "8 GB RAM",
  //     "8 User s Pack",
  //     "200 GB Storage",
  //     "Daily BackUp",
  //     "speed upto 100Mbps",
  //     "99.9% uptime",
  //     "24*7 Support",
  //   ],
  // },

  // {
  //   type: "Cloud VPS V8",
  //   rs: "₹15000",
  //   tx: "Basic features:",
  //   ft: [
  //     "8 vCore CPU",
  //     "16 GB RAM",
  //     "15 User s Pack",
  //     "400 GB Storage",
  //     "Daily BackUp",
  //     "speed upto 100Mbps",
  //     "99.9% uptime",
  //     "24*7 Support",
  //   ],
  // },

  {
    server: "GPU CLOUD SERVER",
    type: "Cloud VPS V8",
    rs: "₹7000",
    tx: "Basic features:",
    xx: "User / Month",
    ft: [
      "8 vCore CPU",
      "4 GB RAM",
      "150 GB Storage",
      "Daily BackUp",
      "speed upto 100Mbps",
      "99.9% uptime",
      "24*7 Support",
    ],
  },
  {
    server: "GPU CLOUD SERVER",
    type: "Cloud VPS V16",
    rs: "₹14000",
    xx: "User / Month",
    tx: "Basic features:",
    ft: [
      "16 vCore CPU",
      "32GB RAM",
      "200 GB Storage",
      "Daily BackUp",
      "speed upto 100Mbps",
      "99.9% uptime",
      "24*7 Support",
    ],
  },
  {
    server: "GPU CLOUD SERVER",
    type: "Cloud VPS V20",
    rs: "₹24000",
    tx: "Basic features:",
    xx: "User / Month",
    ft: [
      "20 vCore CPU",
      "64 GB RAM",
      "400 GB Storage",
      "Daily BackUp",
      "speed upto 100Mbps",
      "99.9% uptime",
      "24*7 Support",
    ],
  },
];

export const pfData7 = [
  {
    server: "GPU CLOUD SERVER",
    type: "Cloud VPS V8",
    rs: "₹7000",
    tx: "Basic features:",
    ft: [
      "8 vCore CPU",
      "4 GB RAM",
      "150 GB Storage",
      "Daily BackUp",
      "speed upto 100Mbps",
      "99.9% uptime",
      "24*7 Support",
    ],
  },
  {
    server: "GPU CLOUD SERVER",
    type: "Cloud VPS V16",
    rs: "₹14000",
    tx: "Basic features:",
    ft: [
      "16 vCore CPU",
      "32GB RAM",
      "200 GB Storage",
      "Daily BackUp",
      "speed upto 100Mbps",
      "99.9% uptime",
      "24*7 Support",
    ],
  },
  {
    server: "GPU CLOUD SERVER",
    type: "Cloud VPS V20",
    rs: "₹24000",
    tx: "Basic features:",
    ft: [
      "20 vCore CPU",
      "64 GB RAM",
      "400 GB Storage",
      "Daily BackUp",
      "speed upto 100Mbps",
      "99.9% uptime",
      "24*7 Support",
    ],
  },
];

export const pfData6 = [
  // {
  //   type: "Cloud VPS V4",
  //   rs: "₹3500",
  //   tx: "Basic features:",
  //   ft: [
  //     "4 vCore CPU",
  //     "4 GB RAM",
  //     "4 User s Pack",
  //     "100 GB Storage",
  //     "Daily BackUp",
  //     "speed upto 100Mbps",
  //     "99.9% uptime",
  //     "24*7 Support",
  //   ],
  // },
  // {
  //   type: "Cloud VPS Premium",
  //   rs: "₹7500",
  //   tx: "Basic features:",
  //   ft: [
  //     "6 vCore CPU",
  //     "8 GB RAM",
  //     "8 User s Pack",
  //     "200 GB Storage",
  //     "Daily BackUp",
  //     "speed upto 100Mbps",
  //     "99.9% uptime",
  //     "24*7 Support",
  //   ],
  // },

  // {
  //   type: "Cloud VPS V8",
  //   rs: "₹15000",
  //   tx: "Basic features:",
  //   ft: [
  //     "8 vCore CPU",
  //     "16 GB RAM",
  //     "15 User s Pack",
  //     "400 GB Storage",
  //     "Daily BackUp",
  //     "speed upto 100Mbps",
  //     "99.9% uptime",
  //     "24*7 Support",
  //   ],
  // },

  {
    server: "GPU CLOUD SERVER",
    type: "Cloud VPS V8",
    rs: "₹7000",
    tx: "Basic features:",
    ft: [
      "8 vCore CPU",
      "4 GB RAM",
      "150 GB Storage",
      "Daily BackUp",
      "speed upto 100Mbps",
      "99.9% uptime",
      "24*7 Support",
    ],
  },
  {
    server: "GPU CLOUD SERVER",
    type: "Cloud VPS V16",
    rs: "₹14000",
    tx: "Basic features:",
    ft: [
      "16 vCore CPU",
      "32GB RAM",
      "200 GB Storage",
      "Daily BackUp",
      "speed upto 100Mbps",
      "99.9% uptime",
      "24*7 Support",
    ],
  },
  {
    server: "GPU CLOUD SERVER",
    type: "Cloud VPS V20",
    rs: "₹24000",
    tx: "Basic features:",
    ft: [
      "20 vCore CPU",
      "64 GB RAM",
      "400 GB Storage",
      "Daily BackUp",
      "speed upto 100Mbps",
      "99.9% uptime",
      "24*7 Support",
    ],
  },
];

export const pfData5 = [
  {
    xy: "Domain Validation Certificates",
    type: "PositiveSSL DV Certificates",
    xx: "Per Year",
    rs: "₹3850",
    tx: "Basic features:",
    ft: [
      "Boosts Google® rankings",
      "Strong SHA-2 & 2048-bit encryption",
      "Displays trust indicator in address bar",
      "24/7 expert support — always there for you",
    ],
  },
  {
    xy: "Organization Validation Certificates",
    type: "PositiveSSL OV Certificates",
    xx: "Per Year",
    rs: "₹7250",
    tx: "Basic features:",
    ft: [
      "Boosts Google® rankings",
      "Strong SHA-2 & 2048-bit encryption",
      "Displays trust indicator in address bar",
      "24/7 expert support — always there for you",
    ],
  },
  {
    xy: "Extended Validation Certificates",
    type: "PositiveSSL EV Certificates",
    xx: "Per Year",
    rs: "₹10500",
    tx: "Basic features:",
    ft: [
      "Boosts Google® rankings",
      "Strong SHA-2 & 2048-bit encryption",
      "Displays trust indicator in address bar",
      "24/7 expert support — always there for you",
    ],
  },
];

export const pfData4 = [
  {
    server: "Premium Email Hosting",
    type: "Premium Email Hosting",
    rs: "₹850",
    xx: "Email / Year",
    tx: "Basic features:",
    ft: [
      "Minimum Per Email Storage 20 GB",
      "AntiSpam/Antivirus Management",
      "Activity, Status & Health Monitoring With SSL",
      "IMAP/POP3",
      "Admin  Management Console",
      "SPAM Filter and Protection",
      "Mail Archival",
      "Email Blacklist/Whitelist",
      "Backup option (Paid)",
    ],
  },

  {
    server: "Microsoft 365 Business Basic",
    type: "Microsoft 365 Business Basic",
    rs: "₹1450",
    xx: "Email / Year",
    tx: "Basic features:",
    ft: [
      "Web and mobile versions of Microsoft 365 apps only",
      "Chat, call, meet up to 300 attendees",
      "1 TB of cloud storage per user",
      "Business-class email",
      "Standard security",
      "Anytime phone and web support",
    ],
  },
  {
    server: "GPU CLOUD SERVER",
    type: "G- Suite Business Starter",
    rs: "₹1650",
    xx: "Email / Year",
    tx: "Basic features:",
    ft: [
      "Custom and secure business email",
      "100-participant video meetings",
      "30 GB storage per user",
      "Security and management controls",
      "Standard support 24*7",
    ],
  },
];

export const pfData3 = [
  {
    server: "Cloud Backup Solution",
    type: "Cloud Backup Solution",
    rs: "₹8/GB",
    tx: "Basic features:",
    xx: "GB/MONTH",
    ft: [
      "Incremental Backup",
      "Drive/File & Entire Machine Backup",
      "Image Label Backup",
      "60% file compression",
      "Admin & User Control Management",
      "Full-stack anti-malware protection",
      "Global and local allowlists from backups",
      "Event-based backup scheduling",
      "Per GB Cost (Min. 100 GB)",
    ],
  },
  {
    server: "Premium Cloud Backup Solution",
    type: "Premium Cloud Backup Solution",
    rs: "₹10/GB",
    tx: "Basic features:",
    xx: "GB/MONTH",
    ft: [
      "Incremental Backup",
      "Drive/File & Entire Machine Backup",
      "Image Label Backup",
      "60% file compression",
      "Admin & User Control Management",
      "Full-stack anti-malware protection",
      "Global and local allowlists from backups",
      "Event-based backup scheduling",
      "Patch Managemnet",
      "Per GB Cost (Min. 100 GB)",
    ],
  },
  {
    server: "On Premise Backup Solution",
    type: "On Premise Backup Solution",
    rs: "₹3000",
    tx: "Basic features:",
    xx: "DEVICE/MONTH",
    ft: [
      "Incremental Backup",
      "Drive/File & Entire Machine Backup",
      "Image Label Backup",
      "60% file compression",
      "Admin & User Control Management",
      "Full-stack anti-malware protection",
      "Global and local allowlists from backups",
      "Event-based backup scheduling",
      "Patch Managemnet",
      "Per GB Cost (Min. 100 GB)",
      "Per Device Cost",
    ],
  },
];

export const pfData2 = [
  {
    server: "GPU CLOUD SERVER",
    type: "Dedicated Server Starter ",
    rs: "₹10500",
    xx: "User/Month",
    tx: "Basic features:",
    ft: [
      "8vCPU Cores",
      "16 GB RAM ",
      "250 GB NVME Storage",
      "Daily BackUp",
      "Free Data Migration",
      "Daily backups",
      "Support 24*7",
    ],
  },
  {
    server: "GPU CLOUD SERVER",
    type: "Dedicated Server Standard",
    rs: "₹16500",
    tx: "Basic features:",
    ft: [
      "12 vCore CPU",
      "20 GB RAM",
      "250 GB Storage",
      "Daily BackUp",
      "Free Data Migration",
      "24*7 Support",
    ],
  },
  {
    server: "Dedicated Server Premium",
    type: "Dedicated Server Premium",
    rs: "₹21500",
    tx: "Basic features:",
    ft: [
      "16 vCore CPU",
      "32 GB RAM",
      "250 GB Storage",
      "Daily BackUp",
      "99.9% uptime",
      "24*7 Support",
    ],
  },
];

export const images = [
  "https://desktime.com/static/web/_common/awards/g2-leader-summer-2022.png",
  "https://desktime.com/static/web/_common/awards/g2-leader-europe-summer-2022.png",
  "https://desktime.com/static/web/_common/awards/g2-leader-asia-summer-2022.png",
  "https://desktime.com/static/web/_common/awards/capterra-badge.png",
  "https://desktime.com/static/web/_common/awards/softwareadvice-badge-2022.png",
  "https://desktime.com/static/web/_common/awards/30daymoneyback-award.png",
];
